### ISSUE TITLE
1-Click deploy to Vercel

### ISSUE THREAD

**Issue by juzhiyuan** [api7/contributor-graph#38]
Just like:
![image](https://user-images.githubusercontent.com/2106987/117101774-86f1bd80-ada9-11eb-93ce-fdaa91801c9a.png)

https://github.com/vercel/commerce

**Comment by Yiyiyimu** [comment]
Ah I didn't get the meaning of this feature

**Comment by juzhiyuan** [comment]
OK, if someone wants to deploy his own site, he could simply click the `Deploy` icon.

**Comment by Yiyiyimu** [comment]
> OK, if someone wants to deploy his own site, he could simply click the `Deploy` icon.

I mean why would people want to deploy on their own sites 🤣 I could not see the benefits of maintaining it at another place

**Comment by juzhiyuan** [comment]
We could publish it to Vercel's marketplace 🤣 

But of course, maintain here is ok for me now.

**Comment by Yiyiyimu** [comment]
> We could publish it to Vercel's marketplace 🤣

That would be cool!! 🤣
