### ISSUE TITLE
bug: need to fix dependencies vulnerabilities alerted from Github

### ISSUE THREAD

**Issue by Yiyiyimu** [api7/contributor-graph#39]
@LiteSun 

![image](https://user-images.githubusercontent.com/34589752/117387422-e5f12880-aeb6-11eb-9384-beb657642ba3.png)

**Comment by LiteSun** [comment]
ok.

**Comment by Yiyiyimu** [comment]
fixed by @juzhiyuan with [renovate bot](https://www.whitesourcesoftware.com/free-developer-tools/renovate)
