### ISSUE TITLE
Incomplete display of vertical coordinates

### ISSUE THREAD

**Issue by LiteSun** [api7/contributor-graph#49]
This problem occurs when viewing data from the ` torvalds/linux `repository

![image](https://user-images.githubusercontent.com/31329157/120125977-4f7e0180-c1ed-11eb-85aa-ea7537adc055.png)

cc @Yiyiyimu

**Comment by Yiyiyimu** [comment]
Thanks for raising it here! @LiteSun could you give me time to get this issue fixed? I planed to propose to add the graph to apache/airflow and met with this issue.

**Comment by LiteSun** [comment]
Plan to have it done by Tuesday of this week
